# .gitlab-ci.yml
image: felicianotech/docker-hugo:0.37

production:
  type: deploy
  before_script:
  - apt-get update
  - apt-get -qq install python python-pip ca-certificates
  - pip install awscli
  script:
  - hugo
  - aws s3 sync public/ s3://$AWS_BUCKET
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
  artifacts:
    paths:
    - public
  only:
  - master

