# .gitlab-ci.yml
image: publysher/hugo


production:
  type: deploy
  before_script:
  - apt-get update
  - apt-get -qq install python python-pip ca-certificates
  - pip install awscli
  script:
  - hugo
  - aws s3 sync public/ s3://$AWS_BUCKET
  artifacts:
    paths:
    - public
  only:
  - master

