steps:
  - name: build
    image: nixos/nix
    commands:
      - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
      - nix build
      - nix flake show
      - ls result
      - nix develop --command wrangler pages deploy result --branch=$CI_COMMIT_SOURCE_BRANCH --project-name=softinio --commit-dirty=true
    secrets: [ cloudflare_account_id, cloudflare_api_token ]
    when:
      event: [push, pull_request]
      branch:
        exclude: [ main ]

  - name: deploy
    image: nixos/nix
    commands:
      - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
      - nix build
      - nix develop --command wrangler pages deploy result --project-name=softinio --commit-dirty=true
    secrets: [ cloudflare_account_id, cloudflare_api_token ]
    when:
      event: push
      branch: main

