baseurl = "https://www.softinio.com/"
title = "Salar Rahmanian"
author = "Salar Rahmanian"
enableRobotsTXT = true
enableEmoji = true
theme = "hugo-clarity"
paginate = 10

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = "--"
    lineNoStart = 1
    lineNos = true # always set to true # else line numbers won't show at all! even when you toggle them on in the UI
    lineNumbersInTable = false # toggling this on (i.e to true) or deleting this line will break the code blocks functionality. Will
    noClasses = false
    # style = "monokai"
    tabWidth = 2
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = false # change to true to enable inclusion of rawHTML and math functions
    xhtml = false

[params]
author = "Salar Rahmanian"
twitter = "@SalarRahmanian"
largeTwitterCard = false
introDescription = "Software Engineer based in San Francisco Bay with interests in Scala, Java"
ga_analytics = "UA-47014432-1"
numberOfTagsShown = 14
fallBackOgImage = "salar.jpg"
codeMaxLines = 10
codeLineNumbers = false
mainSections = ["post"]
centerLogo = false
# logo = "salar.jpg"
figurePositionShow = false
figurePositionLabel = "Figure"
mobileNavigation = "left"

description = "Salar Rahmanian"
keywords = ["Salar", "Rahmanian", "Salar Rahmanian", "Blog", "python", "scala", "haskell", "nix", "NixOS"]

[params.utteranc]
  enable = true
  repo = "softinio/softinio.com"
  issueTerm = "url"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"



[outputs]
  home = ["html", "jsonfeed","rss"]
  page = ["html"]

[outputFormats]
  [outputFormats.jsonfeed]
    mediaType = "application/json"
    baseName = "feed"
    isPlainText = true

[deployment]
order = [".png$", ".jpg$", ".gif$", ".svg$"]

[[deployment.targets]]
name = "softinio-deploy"
URL = "s3://www.softinio.com?region=us-east-1"
cloudFrontDistributionID = "E1CMSLHG2WR51C"

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
