# [[main]]
#   name = "Home"
#   url = ""
#   weight = -110

[[main]]
  name = "About"
  url = "about/"
  weight = -110

[[main]]
  name = "Resume"
  url = "resume/"
  weight = -109

[[main]]
  name = "Consulting"
  url = "consulting/"
  weight = -108

[[main]]
  name = "Newsletter"
  url = "https://notes.softinio.com"
  weight = -107

[[main]]
  name = "Watch"
  url = "https://watch.softinio.com/c/softinio/videos"
  weight = -106

[[main]]
  name = "TIL"
  url = "https://til.softinio.com"
  weight = -105

# Submenus are done this way: parent -> identifier
# [[main]]
#   name = "Links"
#   identifier = "Links"
#   weight = -108
# [[main]]
#   parent = "Links"
#   name = "LinkedIn"
#   url = "https://www.linkedin.com/"
# [[main]]
#   parent = "Links"
#   name = "Twitter"
#   url = "https://twitter.com/"

# [[main]]
#   name = "About"
#   url = "about/"
#   weight = -107

# social menu links

[[social]]
  name = "cgit"
  weight = 1
  url = "http://git.softinio.com"
[[social]]
  name = "github"
  type = "social"
  weight = 2
  url = "https://github.com/softinio"
[[social]]
  name = "twitter"
  weight = 3
  url = "https://twitter.com/SalarRahmanian"
[[social]]
  name = "linkedin"
  weight = 4
  url = "https://www.linkedin.com/in/salarrahmanian"
[[social]]
  name = "youtube"
  weight = 5
  url = "https://softin.io/youtube"
[[social]]
  name = "matrix"
  weight = 6
  url = "https://matrix.to/#/@softinio:matrix.org"
[[social]]
  name = "mastedon"
  weight = 7
  url = "https://fosstodon.org/@softinio"
[[social]]
  name = "rss"
  weight = 8
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"
