name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-primary-key: never

      - name: Build site (pull request)
        if: github.event_name == 'pull_request'
        env:
          BASE_URL: /
        run: |
          # The --impure flag is required to allow access to the BASE_URL environment variable during build evaluation.
          nix build --impure -L

      - name: Deploy to Cloudflare Pages (pull request)
        if: github.event_name == 'pull_request'
        run: |
          npx wrangler@latest pages deploy result --branch=${{ github.head_ref }} --project-name=softinio --commit-dirty=true
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Build site (main branch)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          nix build -L

      - name: Deploy to Cloudflare Pages (main branch)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          npx wrangler@latest pages deploy result --project-name=softinio --commit-dirty=true
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
